### ISSUE TITLE
endpoint Crear turno médico (POST)

### ISSUE THREAD

**Issue by Tilk1** [Tilk1/softtek-obra-social-grupo07#1]
📍Método HTTP: POST

4

➜ Ruta de la API: /turnos
➜ Descripción: Este endpoint permitirá a los usuarios crear un
nuevo turno médico proporcionando los siguientes datos en el
cuerpo de la solicitud:
↪ Nombre del paciente
↪ Fecha y hora de la cita
↪ ID del médico especialista
↪ Motivo de la consulta

**Comment by darioediaz** [comment]
creado en reama featured/turnos-post-all-endpoint <REVISAR>

**Comment by darioediaz** [comment]
funcionando
