### ISSUE TITLE
endpoint Actualizar turno médico (PUT)

### ISSUE THREAD

**Issue by Tilk1** [Tilk1/softtek-obra-social-grupo07#3]
➜ 📍 Método HTTP: PUT
➜ Ruta de la API: /turnos/{id}
➜ Descripción: Este endpoint permitirá a los usuarios actualizar la
información de un turno médico existente identificado por su ID.
Se deberá enviar en el cuerpo de la solicitud los datos
actualizados, que podrían incluir:
↪ Nueva fecha y hora de la cita
↪ ID del nuevo médico especialista
↪ Nuevo motivo de la consulta

**Comment by darioediaz** [comment]
creando en rama endpoint-put-turno

**Comment by darioediaz** [comment]
en teoria esta funcionando pero no me deja probar hasta tener lo de pacientes y su vinculacion con la base de datos (creo)
