### ISSUE TITLE
endpoint Eliminar turno médico: (DELETE)

### ISSUE THREAD

**Issue by Tilk1** [Tilk1/softtek-obra-social-grupo07#4]
➜ 📍 Método HTTP: DELETE
➜ Ruta de la API: /turnos/{id}
➜ Descripción: Este endpoint permitirá a los usuarios cancelar un
turno médico existente identificado por su ID. No se requerirá
enviar ningún dato en el cuerpo de la solicitud.

**Comment by darioediaz** [comment]
creado en rama feature/delete-turno-endpoint

**Comment by darioediaz** [comment]
funcionando
