### ISSUE TITLE
endpoint Descargar receta médica (GET)

### ISSUE THREAD

**Issue by Tilk1** [Tilk1/softtek-obra-social-grupo07#5]
➜ 📍 Método HTTP: GET

5

➜ Ruta de la API: /recetas/{id}
➜ Descripción: Este endpoint permitirá a los pacientes
autorizados descargar su receta médica proporcionando el ID
del turno asociado a la receta. Se verificará la autenticación del
usuario y la validez de la receta antes de permitir la descarga.

**Comment by imdaviddev** [comment]
Habria que ver o evaluar si el formato de descarga es pdf,img,etc. 
Y por otro lado, si este endpoint devuelve el pdf o si es posible obtener los datos para mostrarlo en el frontend.
